--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/LuthMC/AntiAFKPlus
build-by-default: true
branches:
- master
projects:
  AntiAFKPlus:
    path: ""
    libs:
      - src: Vasync\LSPlaceholderAPI\PlaceHolderAPI
        version: ^1.0.2
...
